"""DuckDuckGo search layer for evidence retrieval.

Sits between the claim extractor and the NLI scorer.
Accepts a search query string generated by the extractor and
returns raw text snippets from DuckDuckGo for use as evidence
in the scoring stage.
"""

from ddgs import DDGS

# Backend whitelist for the underlying DDGS federated search. DDGS's
# ``"auto"`` default rotates across all engines including bing (noisy)
# and yahoo (a bing reskin). Restricting to a curated list biases
# toward higher-quality fact-check sources. Comma-delimited form is
# the documented way to scope ``DDGS().text()``.
DEFAULT_BACKENDS = "duckduckgo,google,brave,mojeek,wikipedia"


def get_search_snippets(
    query: str,
    num_results: int = 5,
    timeout: int = 5,
    backend: str = DEFAULT_BACKENDS,
) -> list[str]:
    """Retrieve raw evidence snippets from DuckDuckGo for a given query.

    Performs a text search and extracts the body text from each result.
    Snippets are passed directly to the scorer without modification so
    the NLI model receives the original web content. Any exception from
    the underlying HTTP client (timeouts, rate limits, DNS failures,
    library changes) is caught and turned into an empty result list so
    one transient search failure cannot kill the whole fact-checking
    stream — the scorer simply produces no ``CheckResult`` for that
    claim and the verdict is silently dropped.

    Args:
        query: A search query string generated by ``Extractor.extract()``.
            Typically a comma-separated topic and keyword string.
        num_results: Maximum number of snippets to return. Defaults to 5.
        timeout: Per-request timeout in seconds for the underlying HTTP
            client. Defaults to 5. Kept low so a stuck search worker
            does not block its orchestrator stage slot for long.
        backend: Comma-delimited list of DDGS backends to query.
            Defaults to ``DEFAULT_BACKENDS`` — a curated set that
            excludes bing, yahoo (bing-powered), yandex, and
            grokipedia, all of which tend to produce noisy results
            for fact-check queries.

    Returns:
        A list of up to ``num_results`` raw snippet strings extracted
        from the body of each search result. Empty results are excluded.
        Returns an empty list if no results are found *or* if the
        search failed for any reason.

    Preconditions:
        - ``query`` is a non-empty string.
        - ``num_results`` and ``timeout`` are positive integers.
        - A network connection is available.

    Postconditions:
        - Returned snippets are stripped of leading and trailing whitespace.
        - Does not mutate any external state.
        - Each returned string is non-empty.
        - Returns ``[]`` on any network or library error rather than
          raising.
    """
    fact_query = f"fact check {query}"
    try:
        results = DDGS(timeout=timeout).text(
            fact_query,
            max_results=num_results,
            backend=backend,
        )
    except Exception:
        return []

    snippets: list[str] = [
        result.get("body", "").strip()
        for result in results[:num_results]
        if result.get("body", "").strip()
    ]

    return snippets