"""DuckDuckGo search layer for evidence retrieval.

Sits between the claim extractor and the NLI scorer.
Accepts a search query string generated by the extractor and
returns raw text snippets from DuckDuckGo for use as evidence
in the scoring stage.
"""

from concurrent.futures import ThreadPoolExecutor
from datetime import date

from ddgs import DDGS

# Backend whitelist for the per-backend parallel search. We
# explicitly call DDGS once per backend instead of using DDGS's
# built-in comma-delimited form so each engine gets its own slot
# in the result pool — DDGS's internal "comma-delimited" mode races
# the engines and returns whichever one fills ``max_results`` first,
# which means a single fast-but-noisy backend (e.g. Google ranking
# an off-topic page highly) can dominate the snippet pool. Calling
# each backend independently and merging guarantees diversity.
#
# - Google: breadth, recency, best general ranking.
# - Wikipedia: encyclopedic corroboration for named entities.
# - Brave: independent crawler-based index, catches items Google
#   deranks or misses.
#
# DuckDuckGo is effectively a Bing reskin so it adds nothing beyond
# what bing would, and Mojeek's index is too small to earn its slot.
DEFAULT_BACKENDS = "google,wikipedia,brave"


def get_search_snippets(
    query: str,
    num_results: int = 5,
    timeout: int = 5,
    backend: str = DEFAULT_BACKENDS,
) -> list[str]:
    """Retrieve raw evidence snippets across every configured backend.

    Spins up one thread per backend, each running an independent
    DDGS search, and aggregates whatever comes back. A backend that
    times out, rate-limits, or raises silently contributes zero
    snippets — the others still return their results, so transient
    per-engine failures degrade gracefully instead of starving the
    whole search. Snippets are deduplicated by exact body match
    across backends so identical hits don't double-count downstream.

    The query is suffixed with today's date in natural-language form
    (e.g. ``"April 22 2026"``) so search rankings bias toward recent
    coverage for time-relative claims. No ``"fact check"`` prefix —
    empirically, that wording biased Google toward meta-discussion
    pages (Snopes/PolitiFact-style rebuttals) rather than primary
    sources stating the facts themselves.

    Args:
        query: A search query string — typically a claim sentence
            from the extractor.
        num_results: Maximum snippets requested *per backend*. Total
            returned can be up to ``num_results × len(backends)``
            before deduplication.
        timeout: Per-request HTTP timeout in seconds for each backend
            call. Defaults to 5. Kept low so a stuck backend does not
            block its orchestrator stage slot for long.
        backend: Comma-delimited list of DDGS backends to query in
            parallel. Defaults to ``DEFAULT_BACKENDS``.

    Returns:
        A list of unique non-empty snippet strings aggregated across
        every backend that returned successfully. Empty list when no
        backend produced any results.

    Preconditions:
        - ``query`` is a non-empty string.
        - ``num_results`` and ``timeout`` are positive integers.
        - A network connection is available.

    Postconditions:
        - Returned snippets are stripped of leading/trailing whitespace.
        - Returned snippets are deduplicated by exact body content.
        - Returns ``[]`` only when every backend failed or returned
          no usable bodies.
        - Does not mutate any external state.
        - Per-backend exceptions are swallowed.
    """
    fact_query = f"{query}. {date.today().strftime('%B %d %Y')}"
    backends = [b.strip() for b in backend.split(",") if b.strip()]
    if not backends:
        return []

    def _search_one(single_backend: str) -> list[str]:
        """Search a single backend and return its body snippets."""
        try:
            results = DDGS(timeout=timeout).text(
                fact_query,
                max_results=num_results,
                backend=single_backend,
            )
        except Exception:
            return []
        return [
            result.get("body", "").strip()
            for result in results[:num_results]
            if result.get("body", "").strip()
        ]

    snippets: list[str] = []
    seen: set[str] = set()
    with ThreadPoolExecutor(max_workers=len(backends)) as pool:
        for per_backend_snippets in pool.map(_search_one, backends):
            for body in per_backend_snippets:
                if body not in seen:
                    seen.add(body)
                    snippets.append(body)

    return snippets
