name: bsnet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.11
  - pytorch::pytorch
  - pytorch::torchaudio
  - numpy
  - pip
  - pip:
      - transformers
      - llama-cpp-python
      - faster-whisper
      - sentencepiece
      - tiktoken
      - webrtcvad-wheels
      - pytest
      - ddgs
