name: bsnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - pip
  - pip:
      - transformers
      - llama-cpp-python
      - faster-whisper
      - sentencepiece
      - tiktoken
      - webrtcvad-wheels
      - pytest
      - ddgs
      - torch
      - torchaudio
      - bitsandbytes
      - accelerate
