"""DuckDuckGo search layer for evidence retrieval.

Sits between the claim extractor and the NLI scorer.
Accepts a search query string generated by the extractor and
returns raw text snippets from DuckDuckGo for use as evidence
in the scoring stage.
"""

from ddgs import DDGS


def get_search_snippets(query: str, num_results: int = 5) -> list[str]:
    """Retrieve raw evidence snippets from DuckDuckGo for a given query.

    Performs a text search and extracts the body text from each result.
    Snippets are passed directly to the scorer without modification so
    the NLI model receives the original web content.

    Args:
        query: A search query string generated by ``Extractor.extract()``.
            Typically a comma-separated topic and keyword string.
        num_results: Maximum number of snippets to return. Defaults to 5.

    Returns:
        A list of up to ``num_results`` raw snippet strings extracted
        from the body of each search result. Empty results are excluded.
        Returns an empty list if no results are found.

    Preconditions:
        - ``query`` is a non-empty string.
        - A network connection is available.

    Postconditions:
        - Returned snippets are stripped of leading and trailing whitespace.
        - Does not mutate any external state.
        - Each returned string is non-empty.
    """
    fact_query = f"fact check {query}"
    results = DDGS().text(fact_query, max_results=num_results)

    snippets: list[str] = [
        result.get("body", "").strip()
        for result in results[:num_results]
        if result.get("body", "").strip()
    ]

    return snippets
